version: 2

models:
  - name: stg_superheroes
    description: "Test"
    columns:
    - name: name 
      tests:
       - not_null 
    
    # - name : height
    #   tests:
    #   - positive_values 
    # - name : weight 
    #   tests :
    #   - positive_values 

  - name: stg_users
    description: >
          contains users contact details. 
          snapshot name -- users_snapshot (strategy -- timestamp)
    columns:
      - name: user_id
        tests:
            - unique
            - not_null
            
               


      - name: stg_addresses        
        description: >
          contains users address details.PK -- ADDRESS_ID
          snapshot name -- addresses_snapshot (strategy -- check)


      - name: stg_events
        loaded_at_field: created_at
        description: >
          contains users event type and page url.PK-- EVENT_ID
          No snapshot this table 
      
      - name: stg_orders
        loaded_at_field: created_at
        description: >
          contains users order details along with tracking with status. PK-- Order_ID and PROMO_ID
          snapshot name -- orders_snapshot (strategy -- timestamp)
        
      - name: stg_order_items        
        description: >
          contains users order quantity per products Primary Key-- Order_ID and PRODUCT_ID
          No snapshot this table 
      
      - name: stg_products
        description: >
          contains products details related to order items.PK -- PRODUCT_ID
          snapshot name -- products_snapshot (strategy -- check)
                
      - name: stg_promos        
        description: >
          contains order promos. PK -- PROMO_ID
          No snapshot this table

      - name: stg_shipments
        description: >
          contains order shipment status